name: Build and push to live
on:
  push:
    branches:
      - live_src

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false

    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run build script
        env:
          SIGNING_KEY: ${{ secrets.GPG_KEY }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          chmod +x ./build-all.sh
          ./build-all.sh

      - name: Push to live
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:live
